-- Run this in Supabase SQL Editor to create the books table
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT,
    status TEXT NOT NULL DEFAULT 'want_to_read',
    start_date DATE,
    end_date DATE,
    rating INT,
    genre TEXT,
    total_pages INT,
    current_page INT DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE books ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public" ON books FOR ALL USING (true) WITH CHECK (true);
