import streamlit as st
import pandas as pd
from db import fetch_all, fetch_games, add_game, insert_row, insert_rows, delete_row, update_row, save_custom_color
from colors import apply_college_theme, clear_color_cache
from auth import require_login

st.set_page_config(page_title="CFB Dynasty", layout="wide")
require_login()

CLASS_AGE = {
    "FR": 19, "SO": 20, "JR": 21, "SR": 22,
    "FR(RS)": 20, "SO(RS)": 21, "JR(RS)": 22, "SR(RS)": 23,
    "RS FR": 20, "RS SO": 21, "RS JR": 22, "RS SR": 23,
}


def age_from_class(class_str):
    if not class_str:
        return None
    return CLASS_AGE.get(class_str.strip().upper())


games = fetch_games("cfb")
selected_game = st.selectbox("Game", list(games.keys()))
table = f"{games[selected_game]}_draft_picks"

with st.sidebar:
    st.subheader("Manage Games")
    with st.expander("Add New CFB Game"):
        new_game_name = st.text_input("Game Name", placeholder="CFB 28", key="new_cfb_name")
        new_game_prefix = st.text_input(
            "Table Prefix", placeholder="cfb28", key="new_cfb_prefix",
            help="Used for database table names",
        )
        if st.button("Add Game", key="add_cfb_game"):
            if new_game_name and new_game_prefix:
                try:
                    add_game("cfb", new_game_name, new_game_prefix)
                    st.success(f"Added {new_game_name}!")
                    st.markdown("**Run this SQL in Supabase SQL Editor:**")
                    st.code(f"""CREATE TABLE IF NOT EXISTS {new_game_prefix}_draft_picks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school TEXT, year INT, name TEXT, position TEXT, class TEXT,
    draft_age INT, height TEXT, weight NUMERIC, number TEXT,
    race TEXT, round TEXT, additional_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE {new_game_prefix}_draft_picks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public" ON {new_game_prefix}_draft_picks
    FOR ALL USING (true) WITH CHECK (true);""")
                except Exception as e:
                    st.error(f"Error: {e}")
            else:
                st.warning("Fill in both fields.")

    with st.expander("Set School Colors"):
        sc_school = st.text_input("School Name", placeholder="Purdue", key="sc_school")
        sc_c1, sc_c2 = st.columns(2)
        sc_primary = sc_c1.color_picker("Primary", "#003366", key="sc_primary")
        sc_secondary = sc_c2.color_picker("Secondary", "#FFFFFF", key="sc_secondary")
        if st.button("Save Colors", key="save_school_colors"):
            if sc_school:
                save_custom_color("college", sc_school.strip(), sc_primary, sc_secondary)
                st.success(f"Saved colors for {sc_school}")
                clear_color_cache()
                st.rerun()
            else:
                st.warning("Enter a school name.")

try:
    data = fetch_all(table, order_col="year")
except Exception:
    data = []
df = pd.DataFrame(data)

if df.empty:
    st.info("No draft pick data loaded yet. Add picks below or run the table SQL from the sidebar.")

schools = sorted(df["school"].unique()) if not df.empty else []
selected_school = st.selectbox("School", schools) if schools else None

apply_college_theme(selected_school)
st.title(f"{selected_game} Draft Tracker")

_has_picks = not df.empty and selected_school is not None

if _has_picks:
    school_df = df[df["school"] == selected_school].sort_values(["year", "round"])

if _has_picks:
    # --- Metrics ---
    round_order = ["1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "UDFA"]
    first_rd = school_df[school_df["round"] == "1st"]
    top_3 = school_df[school_df["round"].isin(["1st", "2nd", "3rd"])]
    years_active = school_df["year"].nunique()

    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("Total Picks", len(school_df))
    col2.metric("1st Rounders", len(first_rd))
    col3.metric("Top 3 Rounds", len(top_3))
    col4.metric("Draft Classes", years_active)
    if years_active > 0:
        col5.metric("Avg Picks/Year", f"{len(school_df) / years_active:.1f}")

    st.divider()

    # --- Filters + Table ---
    filter_col1, filter_col2, filter_col3 = st.columns(3)
    with filter_col1:
        positions = sorted(school_df["position"].dropna().unique())
        sel_positions = st.multiselect("Position", positions)
    with filter_col2:
        rounds = sorted(school_df["round"].dropna().unique())
        sel_rounds = st.multiselect("Round", rounds)
    with filter_col3:
        years = sorted(school_df["year"].dropna().unique())
        sel_years = st.multiselect("Year", [int(y) for y in years])

    filtered = school_df.copy()
    if sel_positions:
        filtered = filtered[filtered["position"].isin(sel_positions)]
    if sel_rounds:
        filtered = filtered[filtered["round"].isin(sel_rounds)]
    if sel_years:
        filtered = filtered[filtered["year"].isin(sel_years)]

    display_cols = ["year", "name", "position", "class", "draft_age", "height", "weight",
                    "number", "race", "round", "additional_notes"]
    cfb_col_names = {
        "year": "Year", "name": "Name", "position": "Pos", "class": "Class",
        "draft_age": "Age", "height": "Ht", "weight": "Wt", "number": "#",
        "race": "Race", "round": "Round", "additional_notes": "Notes",
    }
    edit_df = filtered[["id"] + display_cols].copy()
    edit_df.rename(columns=cfb_col_names, inplace=True)

    edited_cfb = st.data_editor(
        edit_df.set_index("id"),
        use_container_width=True,
        key="edit_cfb",
    )

    cfb_reverse = {v: k for k, v in cfb_col_names.items()}
    if st.button("Save Changes", key="save_cfb"):
        for row_id in edited_cfb.index:
            orig = edit_df[edit_df["id"] == row_id]
            if orig.empty:
                continue
            orig_row = orig.iloc[0]
            updates = {}
            for disp_col in edited_cfb.columns:
                db_col = cfb_reverse.get(disp_col, disp_col)
                new_val = edited_cfb.loc[row_id, disp_col]
                old_val = orig_row.get(disp_col)
                if str(new_val) != str(old_val):
                    updates[db_col] = new_val if pd.notna(new_val) and str(new_val).strip() else None
            if updates:
                update_row(table, int(row_id), updates)
        st.success("Saved.")
        st.rerun()

    export_df = filtered[display_cols].rename(columns=cfb_col_names)
    st.download_button(
        "Download CSV",
        export_df.to_csv(index=False),
        f"{selected_game.lower().replace(' ', '_')}_{selected_school.lower()}_picks.csv",
        "text/csv",
        key="export_cfb",
    )

    with st.expander("Delete Picks"):
        for _, row in filtered.iterrows():
            dc1, dc2 = st.columns([6, 1])
            dc1.caption(f"{row['name']} — {row['position']} (Yr {int(row['year'])}, {row['round']})")
            confirm_key = f"confirm_del_pick_{row['id']}"
            if confirm_key not in st.session_state:
                if dc2.button("Delete", key=f"del_pick_{row['id']}"):
                    st.session_state[confirm_key] = True
                    st.rerun()
            else:
                dc2.warning("Sure?")
                yc, nc = dc2.columns(2)
                if yc.button("Yes", key=f"yes_pick_{row['id']}"):
                    delete_row(table, row["id"])
                    st.session_state.pop(confirm_key, None)
                    st.rerun()
                if nc.button("No", key=f"no_pick_{row['id']}"):
                    st.session_state.pop(confirm_key, None)
                    st.rerun()

    st.divider()

    # --- Analytics Tabs ---
    tab_year, tab_round, tab_pos, tab_class, tab_measurables = st.tabs(
        ["By Year", "By Round", "By Position", "By Class", "Measurables"]
    )

    with tab_year:
        by_year = school_df.groupby("year").size().reset_index(name="count")
        st.bar_chart(by_year.set_index("year")["count"])

        st.markdown("**Round Breakdown by Year**")
        year_round = school_df.groupby(["year", "round"]).size().unstack(fill_value=0)
        for r in round_order:
            if r not in year_round.columns:
                year_round[r] = 0
        year_round = year_round[
            [r for r in round_order if r in year_round.columns]
        ]
        st.dataframe(year_round, use_container_width=True)

        if not first_rd.empty:
            st.markdown("**1st Round Picks**")
            st.dataframe(
                first_rd[["year", "name", "position"]].rename(
                    columns={"year": "Year", "name": "Name", "position": "Pos"}
                ).sort_values("Year", ascending=False),
                use_container_width=True, hide_index=True,
            )

    with tab_round:
        by_round = school_df.groupby("round").size().reset_index(name="count")
        by_round["round"] = pd.Categorical(by_round["round"], categories=round_order, ordered=True)
        by_round = by_round.sort_values("round").dropna(subset=["round"])
        st.bar_chart(by_round.set_index("round")["count"])

        st.markdown("**Best Draft Round by Position**")
        if "position" in school_df.columns:
            round_rank = {r: i for i, r in enumerate(round_order)}
            pos_df = school_df.dropna(subset=["round", "position"]).copy()
            pos_df["round_rank"] = pos_df["round"].map(round_rank)
            best_round_pos = pos_df.groupby("position").agg(
                picks=("name", "count"),
                best_round=("round_rank", "min"),
                avg_round=("round_rank", "mean"),
            ).reset_index()
            best_round_pos["best_round"] = best_round_pos["best_round"].map(
                {i: r for i, r in enumerate(round_order)}
            )
            best_round_pos["avg_round"] = best_round_pos["avg_round"].apply(
                lambda x: round_order[round(x)] if round(x) < len(round_order) else "—"
            )
            st.dataframe(
                best_round_pos.rename(columns={
                    "position": "Position", "picks": "Picks",
                    "best_round": "Highest Pick", "avg_round": "Avg Round",
                }).sort_values("Picks", ascending=False),
                use_container_width=True, hide_index=True,
            )

    with tab_pos:
        st.markdown("**Picks by Position**")
        by_pos = school_df["position"].value_counts()
        st.bar_chart(by_pos)

        st.markdown("**Position Breakdown by Round**")
        pos_round = school_df.groupby(["position", "round"]).size().unstack(fill_value=0)
        for r in round_order:
            if r not in pos_round.columns:
                pos_round[r] = 0
        pos_round = pos_round[[r for r in round_order if r in pos_round.columns]]
        pos_round["Total"] = pos_round.sum(axis=1)
        pos_round = pos_round.sort_values("Total", ascending=False)
        st.dataframe(pos_round, use_container_width=True)

    with tab_class:
        if "class" in school_df.columns:
            st.markdown("**Picks by Class**")
            by_class = school_df["class"].value_counts()
            st.bar_chart(by_class)

            st.markdown("**Class by Round**")
            class_round = school_df.groupby(["class", "round"]).size().unstack(fill_value=0)
            for r in round_order:
                if r not in class_round.columns:
                    class_round[r] = 0
            class_round = class_round[[r for r in round_order if r in class_round.columns]]
            class_round["Total"] = class_round.sum(axis=1)
            class_round = class_round.sort_values("Total", ascending=False)
            st.dataframe(class_round, use_container_width=True)

    with tab_measurables:
        school_df["weight_num"] = pd.to_numeric(school_df["weight"], errors="coerce")
        school_df["age_num"] = pd.to_numeric(school_df["draft_age"], errors="coerce")

        m1, m2, m3 = st.columns(3)
        avg_wt = school_df["weight_num"].mean()
        avg_age = school_df["age_num"].mean()
        if pd.notna(avg_wt):
            m1.metric("Avg Weight", f"{avg_wt:.0f} lbs")
        if pd.notna(avg_age):
            m2.metric("Avg Draft Age", f"{avg_age:.1f}")
        youngest = school_df.loc[school_df["age_num"].idxmin()] if school_df["age_num"].notna().any() else None
        if youngest is not None:
            m3.metric("Youngest Drafted", f"{youngest['name']} ({int(youngest['age_num'])})")

        st.markdown("**Avg Weight by Position**")
        wt_by_pos = school_df.groupby("position")["weight_num"].mean().dropna().sort_values(ascending=False)
        if not wt_by_pos.empty:
            st.bar_chart(wt_by_pos)

        st.markdown("**Draft Age Distribution**")
        if school_df["age_num"].notna().any():
            age_dist = school_df["age_num"].dropna().value_counts().sort_index()
            st.bar_chart(age_dist)

        st.markdown("**Heaviest Picks**")
        heaviest = school_df.nlargest(5, "weight_num")[["name", "position", "weight", "year"]].rename(
            columns={"name": "Name", "position": "Pos", "weight": "Weight", "year": "Year"}
        )
        if not heaviest.empty:
            st.dataframe(heaviest, use_container_width=True, hide_index=True)

        st.markdown("**Lightest Picks**")
        lightest = school_df.nsmallest(5, "weight_num")[["name", "position", "weight", "year"]].rename(
            columns={"name": "Name", "position": "Pos", "weight": "Weight", "year": "Year"}
        )
        if not lightest.empty:
            st.dataframe(lightest, use_container_width=True, hide_index=True)

st.divider()

round_order = ["1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "UDFA"]

# --- Add Data ---
add_single, add_bulk = st.tabs(["Add Single Pick", "Bulk Add"])

with add_single:
    with st.form("add_pick"):
        fc1, fc2, fc3 = st.columns(3)
        new_school = fc1.text_input("School", value=selected_school or "")
        new_year = fc2.number_input("Year", min_value=2024, max_value=2060, value=2027)
        new_name = fc3.text_input("Player Name")
        fc4, fc5, fc6 = st.columns(3)
        new_pos = fc4.text_input("Position")
        new_class = fc5.text_input("Class (e.g., SR, JR(RS))")
        new_round = fc6.selectbox("Round", round_order)
        fc7, fc8, fc9 = st.columns(3)
        new_height = fc7.text_input("Height (e.g., 6'2\")")
        new_weight = fc8.number_input("Weight", min_value=100, max_value=400, value=200)
        new_number = fc9.text_input("Jersey Number")
        new_notes = st.text_input("Additional Notes")
        st.caption("Age is auto-calculated from class (FR=19, SO=20, JR=21, SR=22, +1 for RS)")

        if st.form_submit_button("Add Pick"):
            if new_name:
                calc_age = age_from_class(new_class)
                insert_row(table, {
                    "school": new_school, "year": new_year, "name": new_name,
                    "position": new_pos, "class": new_class, "round": new_round,
                    "draft_age": calc_age, "height": new_height, "weight": new_weight,
                    "number": new_number, "additional_notes": new_notes or None,
                })
                st.success(f"Added {new_name} (age: {calc_age or 'unknown class'})")
                st.rerun()
            else:
                st.error("Player name is required.")

with add_bulk:
    st.markdown("Paste tab-separated rows. Columns:")
    st.code("Year\tName\tPosition\tClass\tDraft Age\tHeight\tWeight\tNumber\tRace\tRound\tNotes")
    bulk_school = st.text_input("School for all rows", value=selected_school or "", key="bulk_school")
    bulk_text = st.text_area("Paste rows here", height=200, key="bulk_cfb")

    if st.button("Preview", key="preview_cfb"):
        if bulk_text.strip():
            rows = []
            for line in bulk_text.strip().split("\n"):
                cols = line.split("\t")
                if len(cols) >= 2:
                    rows.append({
                        "Year": cols[0] if len(cols) > 0 else "",
                        "Name": cols[1] if len(cols) > 1 else "",
                        "Position": cols[2] if len(cols) > 2 else "",
                        "Class": cols[3] if len(cols) > 3 else "",
                        "Draft Age": cols[4] if len(cols) > 4 else "",
                        "Height": cols[5] if len(cols) > 5 else "",
                        "Weight": cols[6] if len(cols) > 6 else "",
                        "Number": cols[7] if len(cols) > 7 else "",
                        "Race": cols[8] if len(cols) > 8 else "",
                        "Round": cols[9] if len(cols) > 9 else "",
                        "Notes": cols[10] if len(cols) > 10 else "",
                    })
            if rows:
                st.dataframe(pd.DataFrame(rows), hide_index=True, use_container_width=True)
                st.session_state["bulk_cfb_parsed"] = rows

    if st.button("Upload", key="upload_cfb"):
        parsed = st.session_state.get("bulk_cfb_parsed", [])
        if not parsed:
            st.error("Preview first to validate the data.")
        else:
            db_rows = []
            for r in parsed:
                name = r.get("Name", "").strip()
                if not name:
                    continue
                year_val = None
                try:
                    year_val = int(float(r.get("Year", "")))
                except (ValueError, TypeError):
                    pass
                age_val = None
                raw_age = r.get("Draft Age", "").strip()
                if raw_age:
                    try:
                        age_val = int(float(raw_age))
                    except (ValueError, TypeError):
                        pass
                if age_val is None:
                    age_val = age_from_class(r.get("Class", ""))
                weight_val = None
                try:
                    weight_val = float(r.get("Weight", "").replace("lbs", "").strip())
                except (ValueError, TypeError):
                    pass
                num = r.get("Number", "").replace("#", "").strip() or None
                db_rows.append({
                    "school": bulk_school,
                    "year": year_val,
                    "name": name,
                    "position": r.get("Position", "").strip() or None,
                    "class": r.get("Class", "").strip() or None,
                    "draft_age": age_val,
                    "height": r.get("Height", "").strip() or None,
                    "weight": weight_val,
                    "number": num,
                    "race": r.get("Race", "").strip() or None,
                    "round": r.get("Round", "").strip() or None,
                    "additional_notes": r.get("Notes", "").strip() or None,
                })
            if db_rows:
                insert_rows(table, db_rows)
                st.success(f"Uploaded {len(db_rows)} picks.")
                st.session_state.pop("bulk_cfb_parsed", None)
                st.rerun()
