import streamlit as st
import colorsys
import json
import base64
import io
from datetime import datetime
from collections import Counter
from PIL import Image
from auth import require_login
from db import fetch_all, insert_row, delete_row, get_setting
from weather import fetch_weather, weather_category

st.set_page_config(page_title="Wardrobe", layout="wide")
require_login()

st.title("Wardrobe")

CATEGORIES = ["Tops", "Bottoms", "Outerwear", "Shoes", "Accessories"]
WEATHER_TAGS = ["Hot (85+)", "Warm (70-85)", "Mild (55-70)", "Cool (40-55)", "Cold (<40)"]
WEATHER_TAG_MAP = {"Hot (85+)": "hot", "Warm (70-85)": "warm", "Mild (55-70)": "mild", "Cool (40-55)": "cool", "Cold (<40)": "cold"}


# ---------- color helpers ----------

def hex_to_hsl(hex_color):
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16) / 255, int(h[2:4], 16) / 255, int(h[4:6], 16) / 255
    hue, light, sat = colorsys.rgb_to_hls(r, g, b)
    return hue * 360, sat * 100, light * 100


def color_name(h, s, l):
    if s < 10:
        if l > 85:
            return "White"
        if l < 15:
            return "Black"
        return "Gray"
    if l < 12:
        return "Black"
    if l > 90:
        return "White"
    names = [
        (0, "Red"), (15, "Red-Orange"), (30, "Orange"), (45, "Gold"),
        (55, "Yellow"), (75, "Yellow-Green"), (100, "Lime"), (130, "Green"),
        (160, "Teal"), (185, "Cyan"), (210, "Blue"), (240, "Indigo"),
        (265, "Violet"), (285, "Purple"), (310, "Magenta"), (335, "Pink"),
        (350, "Rose"), (360, "Red"),
    ]
    for i in range(len(names) - 1):
        if h < names[i + 1][0]:
            name = names[i][1]
            break
    else:
        name = "Red"
    if l < 30:
        return f"Dark {name}"
    if l > 70:
        return f"Light {name}"
    return name


def swatch(hex_color, label="", size=40):
    text_color = "#fff" if hex_to_hsl(hex_color)[2] < 55 else "#222"
    return (
        f'<div style="background:{hex_color};color:{text_color};'
        f'width:{size}px;height:{size}px;border-radius:8px;'
        f'display:inline-flex;align-items:center;justify-content:center;'
        f'font-size:0.55em;font-weight:600;text-align:center;'
        f'border:1px solid rgba(128,128,128,0.3);padding:2px;">'
        f'{label}</div>'
    )


def extract_colors(image_bytes, n=4):
    img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    img = img.resize((40, 40))
    pixels = list(img.getdata())
    quantized = []
    for r, g, b in pixels:
        qr, qg, qb = (r // 24) * 24, (g // 24) * 24, (b // 24) * 24
        quantized.append((min(qr, 255), min(qg, 255), min(qb, 255)))
    counter = Counter(quantized)
    top = counter.most_common(n * 3)
    results = []
    for (r, g, b), _ in top:
        hex_c = f"#{r:02x}{g:02x}{b:02x}"
        h, s, l = hex_to_hsl(hex_c)
        too_close = False
        for existing in results:
            eh, es, el = hex_to_hsl(existing)
            if abs(eh - h) < 20 and abs(es - s) < 15 and abs(el - l) < 15:
                too_close = True
                break
        if not too_close:
            results.append(hex_c)
        if len(results) >= n:
            break
    return results


def resize_thumbnail(image_bytes, max_size=300):
    img = Image.open(io.BytesIO(image_bytes))
    img.thumbnail((max_size, max_size))
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=80)
    return buf.getvalue()


def colors_compatible(c1_hex, c2_hex):
    h1, s1, l1 = hex_to_hsl(c1_hex)
    h2, s2, l2 = hex_to_hsl(c2_hex)
    if s1 < 12 or l1 < 12 or l1 > 88:
        return True
    if s2 < 12 or l2 < 12 or l2 > 88:
        return True
    hue_diff = min(abs(h1 - h2), 360 - abs(h1 - h2))
    if hue_diff < 40:
        return True
    if 150 < hue_diff < 210:
        return True
    if 100 < hue_diff < 140 or 220 < hue_diff < 260:
        return True
    return False


# ---------- load data ----------

try:
    _wardrobe_data = fetch_all("wardrobe_items", order_col="created_at")
except Exception:
    _wardrobe_data = None

if _wardrobe_data is None:
    st.error("Table `wardrobe_items` not found. Create it in Supabase:")
    st.code(
        "create table wardrobe_items (\n"
        "    id bigint generated by default as identity primary key,\n"
        "    name text not null,\n"
        "    category text not null,\n"
        "    colors jsonb,\n"
        "    weather_tags jsonb,\n"
        "    image_b64 text,\n"
        "    is_layer boolean default false,\n"
        "    created_at timestamptz default now()\n"
        ");\n\n"
        "alter table wardrobe_items enable row level security;\n"
        "create policy \"Allow All\" on wardrobe_items for all using (true) with check (true);",
        language="sql",
    )
    st.stop()

_items = _wardrobe_data

# ---------- weather context ----------

_saved_loc = get_setting("wardrobe_location")
_lat, _lon, _city = None, None, None
if _saved_loc:
    try:
        _loc = json.loads(_saved_loc)
        _lat, _lon, _city = _loc["lat"], _loc["lon"], _loc.get("city")
    except Exception:
        pass

_weather_cat = None
_current_temp = None
_current_feels = None
if _lat and _lon:
    _wx = fetch_weather(_lat, _lon, days=1)
    if _wx and "hourly" in _wx:
        _now_h = datetime.now().hour
        _current_temp = _wx["hourly"]["temperature_2m"][min(_now_h, 23)]
        _apparent = _wx["hourly"].get("apparent_temperature", _wx["hourly"]["temperature_2m"])
        _current_feels = _apparent[min(_now_h, 23)]
        _weather_cat = weather_category(_current_feels)

if _weather_cat and _current_temp is not None:
    _feels_note = f" (feels {_current_feels:.0f}°F)" if _current_feels is not None and abs(_current_feels - _current_temp) >= 2 else ""
    st.caption(f"{_current_temp:.0f}°F{_feels_note}{f' in {_city}' if _city else ''} — dressing for **{_weather_cat}**")

# ============================================================
# BUILD AN OUTFIT
# ============================================================

if _items:
    st.subheader("Build an Outfit")

    _filter_weather = False
    if _weather_cat:
        _filter_weather = st.checkbox("Filter by today's weather", value=True, key="wx_filter")

    _options = [""]
    _item_map = {}
    for cat in CATEGORIES:
        for item in _items:
            if item.get("category") == cat:
                key = f"{cat}: {item['name']}"
                _options.append(key)
                _item_map[key] = item

    _sel = st.selectbox(
        "piece", _options,
        format_func=lambda x: x or "Pick an item to build around...",
        label_visibility="collapsed",
    )

    if _sel and _sel in _item_map:
        _anchor = _item_map[_sel]
        _a_cat = _anchor.get("category")
        _a_colors = _anchor.get("colors") or []
        _a_layer = _anchor.get("is_layer", False)

        _hc1, _hc2 = st.columns([1, 5])
        with _hc1:
            if _anchor.get("image_b64"):
                st.image(base64.b64decode(_anchor["image_b64"]), width=140)
        with _hc2:
            st.markdown(f"**{_anchor['name']}**")
            if _a_colors:
                _sw = "".join(swatch(c, color_name(*hex_to_hsl(c)), 28) for c in _a_colors)
                st.markdown(f'<div style="display:flex;gap:4px;margin:4px 0;">{_sw}</div>', unsafe_allow_html=True)
            _tags = []
            if _a_layer:
                _tags.append("Layer")
            _wt = _anchor.get("weather_tags") or []
            if _wt:
                _tags.extend(_wt)
            if _tags:
                st.caption(", ".join(_tags))

        def _ok(item, category=None, layer=None):
            if item["id"] == _anchor["id"]:
                return False
            if category and item.get("category") != category:
                return False
            if layer is not None and item.get("is_layer", False) != layer:
                return False
            ic = item.get("colors") or []
            if ic and _a_colors:
                if not any(colors_compatible(ac, c) for ac in _a_colors for c in ic):
                    return False
            if _filter_weather and _weather_cat:
                wt = item.get("weather_tags") or []
                if wt and _weather_cat not in wt:
                    return False
            return True

        _roles = []
        if _a_cat == "Tops" and not _a_layer:
            _roles = [
                ("Bottoms", [i for i in _items if _ok(i, "Bottoms")]),
                ("Layer", [i for i in _items if _ok(i, layer=True)]),
                ("Outerwear", [i for i in _items if _ok(i, "Outerwear", layer=False)]),
                ("Shoes", [i for i in _items if _ok(i, "Shoes")]),
            ]
        elif _a_cat == "Tops" and _a_layer:
            _roles = [
                ("Base Top", [i for i in _items if _ok(i, "Tops", layer=False)]),
                ("Bottoms", [i for i in _items if _ok(i, "Bottoms")]),
                ("Shoes", [i for i in _items if _ok(i, "Shoes")]),
            ]
        elif _a_cat == "Bottoms":
            _roles = [
                ("Tops", [i for i in _items if _ok(i, "Tops", layer=False)]),
                ("Layer", [i for i in _items if _ok(i, layer=True)]),
                ("Outerwear", [i for i in _items if _ok(i, "Outerwear", layer=False)]),
                ("Shoes", [i for i in _items if _ok(i, "Shoes")]),
            ]
        elif _a_cat == "Outerwear":
            _roles = [
                ("Tops", [i for i in _items if _ok(i, "Tops", layer=False)]),
                ("Bottoms", [i for i in _items if _ok(i, "Bottoms")]),
                ("Shoes", [i for i in _items if _ok(i, "Shoes")]),
            ]
        elif _a_cat in ("Shoes", "Accessories"):
            _roles = [
                ("Tops", [i for i in _items if _ok(i, "Tops", layer=False)]),
                ("Bottoms", [i for i in _items if _ok(i, "Bottoms")]),
            ]

        _any = False
        for _rname, _ritems in _roles:
            if not _ritems:
                continue
            _any = True
            st.markdown(f"**{_rname}**")
            _nc = min(len(_ritems), 4)
            _rc = st.columns(_nc)
            for _ri, _rit in enumerate(_ritems[:8]):
                with _rc[_ri % _nc]:
                    if _rit.get("image_b64"):
                        st.image(base64.b64decode(_rit["image_b64"]), width=120)
                    st.caption(_rit["name"])
                    _ric = _rit.get("colors") or []
                    if _ric:
                        _rs = "".join(swatch(c, "", 18) for c in _ric)
                        st.markdown(f'<div style="display:flex;gap:2px;">{_rs}</div>', unsafe_allow_html=True)

        if not _any:
            st.caption("No color-compatible matches found for today's weather. Try unchecking the weather filter.")

else:
    st.info("Add items to your closet below to start building outfits.")

st.divider()

# ============================================================
# MY CLOSET
# ============================================================

st.subheader("My Closet")

if not _items:
    st.caption("Empty — add items below.")
else:
    _cat_tabs = st.tabs(CATEGORIES)
    for _ci, _cat in enumerate(CATEGORIES):
        with _cat_tabs[_ci]:
            _cat_items = [it for it in _items if it.get("category") == _cat]
            if not _cat_items:
                st.caption("Nothing here yet.")
                continue
            _cols = st.columns(4)
            for _ii, _item in enumerate(_cat_items):
                with _cols[_ii % 4]:
                    if _item.get("image_b64"):
                        st.image(base64.b64decode(_item["image_b64"]), width=150)
                    st.markdown(f"**{_item['name']}**")
                    _ic = _item.get("colors") or []
                    if _ic:
                        _sw = "".join(swatch(c, "", 24) for c in _ic)
                        st.markdown(
                            f'<div style="display:flex;gap:4px;margin:4px 0;">{_sw}</div>',
                            unsafe_allow_html=True,
                        )
                    _tp = []
                    if _item.get("is_layer"):
                        _tp.append("Layer")
                    _wt = _item.get("weather_tags") or []
                    if _wt:
                        _tp.extend(_wt)
                    if _tp:
                        st.caption(", ".join(_tp))

st.divider()

# ============================================================
# ADD ITEM
# ============================================================

with st.expander("Add Item"):
    _up_file = st.file_uploader("Photo", type=["jpg", "jpeg", "png", "webp"], key="ward_upload")
    _ac1, _ac2 = st.columns(2)
    _item_name = _ac1.text_input("Name", placeholder="e.g. Blue Nike Dri-Fit")
    _item_cat = _ac2.selectbox("Category", CATEGORIES)
    _default_weather = [] if _item_cat in ("Shoes", "Accessories") else ["Warm (70-85)", "Mild (55-70)"]
    _item_weather = st.multiselect("Suitable weather", WEATHER_TAGS, default=_default_weather)
    _is_layer = False
    if _item_cat in ("Tops", "Outerwear"):
        _is_layer = st.checkbox(
            "Layering piece",
            help="Can be worn open/unbuttoned over another top (flannel, hoodie, button-up, etc.)",
        )

    _extracted = []
    _img_b64 = None

    if _up_file:
        _raw = _up_file.read()
        st.image(_raw, width=200)
        _extracted = extract_colors(_raw, n=4)
        _thumb = resize_thumbnail(_raw, 300)
        _img_b64 = base64.b64encode(_thumb).decode()

        if _extracted:
            st.markdown("**Detected colors:**")
            _sw = "".join(swatch(c, color_name(*hex_to_hsl(c)), 50) for c in _extracted)
            st.markdown(f'<div style="display:flex;gap:6px;margin:8px 0;">{_sw}</div>', unsafe_allow_html=True)

    if st.button("Save Item", key="save_ward") and _item_name.strip():
        _tags = [WEATHER_TAG_MAP[w] for w in _item_weather]
        insert_row("wardrobe_items", {
            "name": _item_name.strip(),
            "category": _item_cat,
            "colors": _extracted if _extracted else None,
            "weather_tags": _tags,
            "image_b64": _img_b64,
            "is_layer": _is_layer,
        })
        st.success(f"Added {_item_name.strip()}!")
        st.rerun()

# ============================================================
# DELETE ITEMS
# ============================================================

if _items:
    with st.expander("Delete Items"):
        for _item in _items:
            _dc1, _dc2, _dc3 = st.columns([1, 8, 1])
            if _item.get("image_b64"):
                _dc1.image(base64.b64decode(_item["image_b64"]), width=40)
            _dc2.caption(f"{_item['name']} ({_item.get('category', '')})")
            if _dc3.button("X", key=f"del_w_{_item['id']}"):
                delete_row("wardrobe_items", _item["id"])
                st.rerun()
