import streamlit as st
import pandas as pd
from datetime import datetime
from zoneinfo import ZoneInfo
from db import fetch_all, insert_row, update_row, delete_row
from auth import require_login

st.set_page_config(page_title="Lyrics", layout="wide")
require_login()

st.title("Lyrics")

try:
    lyrics_data = fetch_all("lyrics", order_col="updated_at")
except Exception:
    lyrics_data = None

try:
    rhyme_data = fetch_all("rhymes", order_col="rhyme_group")
except Exception:
    rhyme_data = []
rhyme_df = pd.DataFrame(rhyme_data)

if lyrics_data is None:
    st.warning("Create the `lyrics` table in Supabase:")
    st.code(
        "create table lyrics (\n"
        "    id bigint generated by default as identity primary key,\n"
        "    title text not null,\n"
        "    content text default '',\n"
        "    status text default 'draft',\n"
        "    created_at timestamptz default now(),\n"
        "    updated_at timestamptz default now()\n"
        ");",
        language="sql",
    )
    st.stop()

lyrics_df = pd.DataFrame(lyrics_data)
today = datetime.now(ZoneInfo("America/Indiana/Indianapolis"))

STATUS_LABELS = {"draft": "Draft", "in_progress": "In Progress", "finished": "Finished"}

lookup_col, write_col = st.columns([1, 3])

with lookup_col:
    st.subheader("Rhyme Lookup")
    lookup = st.text_input("Find rhymes for", placeholder="Type a word...")
    if lookup and not rhyme_df.empty:
        matches = rhyme_df[rhyme_df["word"].str.contains(lookup, case=False, na=False)]
        if not matches.empty:
            seen = set()
            for _, m in matches.iterrows():
                gid = m["rhyme_group"]
                if gid in seen:
                    continue
                seen.add(gid)
                group_words = rhyme_df[rhyme_df["rhyme_group"] == gid]["word"].tolist()
                highlighted = []
                for w in group_words:
                    if lookup.lower() in w.lower():
                        highlighted.append(f"**{w}**")
                    else:
                        highlighted.append(w)
                st.markdown(" / ".join(highlighted))
        else:
            st.caption("No matches.")
    elif lookup:
        st.caption("No rhyme data loaded.")

with write_col:
    if not lyrics_df.empty:
        options = ["+ New"] + lyrics_df["title"].tolist()
        selected = st.selectbox("Select lyric", options, label_visibility="collapsed")
    else:
        selected = "+ New"

    if selected == "+ New":
        with st.form("new_lyric", clear_on_submit=True):
            new_title = st.text_input("Title")
            new_content = st.text_area("Write your bars", height=400, placeholder="Start writing...")
            new_status = st.selectbox(
                "Status", list(STATUS_LABELS.keys()),
                format_func=lambda x: STATUS_LABELS[x],
            )
            if st.form_submit_button("Save"):
                if new_title.strip():
                    insert_row("lyrics", {
                        "title": new_title.strip(),
                        "content": new_content,
                        "status": new_status,
                    })
                    st.success(f"Saved '{new_title.strip()}'")
                    st.rerun()
                else:
                    st.error("Title required.")
    else:
        lyric = lyrics_df[lyrics_df["title"] == selected].iloc[0]
        with st.form(f"edit_lyric_{lyric['id']}"):
            edit_title = st.text_input("Title", value=lyric["title"])
            edit_content = st.text_area("Content", value=lyric.get("content") or "", height=400)
            current_status = lyric.get("status", "draft")
            status_index = list(STATUS_LABELS.keys()).index(current_status) if current_status in STATUS_LABELS else 0
            edit_status = st.selectbox(
                "Status", list(STATUS_LABELS.keys()),
                index=status_index,
                format_func=lambda x: STATUS_LABELS[x],
            )
            if edit_content:
                bars = [l for l in edit_content.split("\n") if l.strip()]
                words = len(edit_content.split())
                st.caption(f"{len(bars)} bars | {words} words")
            if st.form_submit_button("Save Changes"):
                update_row("lyrics", int(lyric["id"]), {
                    "title": edit_title.strip(),
                    "content": edit_content,
                    "status": edit_status,
                    "updated_at": today.isoformat(),
                })
                st.success("Saved.")
                st.rerun()

        ck = f"confirm_del_lyric_{lyric['id']}"
        if st.session_state.get(ck):
            st.warning(f"Delete **{lyric['title']}**?")
            yc, nc = st.columns(2)
            if yc.button("Yes", key=f"yes_lyric_{lyric['id']}"):
                delete_row("lyrics", lyric["id"])
                st.session_state.pop(ck, None)
                st.rerun()
            if nc.button("No", key=f"no_lyric_{lyric['id']}"):
                st.session_state.pop(ck, None)
                st.rerun()
        else:
            if st.button("Delete", key=f"del_lyric_{lyric['id']}"):
                st.session_state[ck] = True
                st.rerun()

if not lyrics_df.empty:
    st.divider()
    with st.expander(f"All Lyrics ({len(lyrics_df)})"):
        for _, lyric in lyrics_df.iterrows():
            status = STATUS_LABELS.get(lyric.get("status", "draft"), "Draft")
            bars = len([l for l in (lyric.get("content") or "").split("\n") if l.strip()])
            words = len((lyric.get("content") or "").split())
            st.caption(f"[{status}] **{lyric['title']}** | {bars} bars | {words} words")
