import streamlit as st
import pandas as pd
import re
from datetime import datetime
from zoneinfo import ZoneInfo
from db import fetch_all, insert_row, update_row, delete_row
from auth import require_login

st.set_page_config(page_title="Lyrics", layout="wide")
require_login()

st.title("Lyrics")

try:
    lyrics_data = fetch_all("lyrics", order_col="updated_at")
except Exception:
    lyrics_data = None

try:
    rhyme_data = fetch_all("rhymes", order_col="rhyme_group")
except Exception:
    rhyme_data = []
rhyme_df = pd.DataFrame(rhyme_data)

if lyrics_data is None:
    st.warning("Create the `lyrics` table in Supabase:")
    st.code(
        "create table lyrics (\n"
        "    id bigint generated by default as identity primary key,\n"
        "    title text not null,\n"
        "    content text default '',\n"
        "    status text default 'draft',\n"
        "    created_at timestamptz default now(),\n"
        "    updated_at timestamptz default now()\n"
        ");",
        language="sql",
    )
    st.stop()

lyrics_df = pd.DataFrame(lyrics_data)
today = datetime.now(ZoneInfo("America/Indiana/Indianapolis"))

STATUS_LABELS = {"draft": "Draft", "in_progress": "In Progress", "finished": "Finished"}


# ---------- syllable + rhyme helpers ----------

def _count_syllables(word):
    word = re.sub(r'[^a-z]', '', word.lower())
    if not word:
        return 0
    count = 0
    prev_vowel = False
    for ch in word:
        is_v = ch in "aeiouy"
        if is_v and not prev_vowel:
            count += 1
        prev_vowel = is_v
    if word.endswith("e") and count > 1:
        count -= 1
    if word.endswith("le") and len(word) > 2 and word[-3] not in "aeiouy":
        count += 1
    return max(count, 1)


def _line_syllables(line):
    words = re.findall(r"[a-zA-Z']+", line)
    return sum(_count_syllables(w) for w in words)


def _last_word(line):
    words = re.findall(r"[a-zA-Z']+", line)
    return words[-1].lower() if words else ""


def _find_rhymes(word, rhyme_df):
    if rhyme_df.empty or not word:
        return []
    matches = rhyme_df[rhyme_df["word"].str.lower() == word.lower()]
    if matches.empty:
        matches = rhyme_df[rhyme_df["word"].str.lower().str.contains(re.escape(word.lower()), na=False)]
    if matches.empty:
        return []
    results = []
    seen_groups = set()
    for _, m in matches.iterrows():
        gid = m["rhyme_group"]
        if gid in seen_groups:
            continue
        seen_groups.add(gid)
        group_words = rhyme_df[rhyme_df["rhyme_group"] == gid]["word"].tolist()
        results.extend([w for w in group_words if w.lower() != word.lower()])
    return results


def _detect_scheme(lines, rhyme_df):
    if rhyme_df.empty:
        return []
    scheme = []
    end_words = [_last_word(l) for l in lines]
    group_map = {}
    for _, row in rhyme_df.iterrows():
        group_map.setdefault(row["word"].lower(), set()).add(row["rhyme_group"])

    labels = {}
    next_label = 0
    result = []
    for i, word in enumerate(end_words):
        if not word:
            result.append("-")
            continue
        assigned = False
        word_groups = group_map.get(word, set())
        for j in range(i):
            prev_word = end_words[j]
            prev_groups = group_map.get(prev_word, set())
            if word_groups & prev_groups or word == prev_word:
                result.append(result[j])
                assigned = True
                break
        if not assigned:
            label = chr(65 + (next_label % 26))
            result.append(label)
            next_label += 1
    return result


# ---------- layout ----------

lookup_col, write_col = st.columns([1, 3])

with lookup_col:
    st.subheader("Rhyme Lookup")
    lookup = st.text_input("Find rhymes for", placeholder="Type a word...")
    if lookup:
        matches = _find_rhymes(lookup, rhyme_df)
        if matches:
            st.markdown(" / ".join(f"**{w}**" if lookup.lower() in w.lower() else w for w in matches))
        elif not rhyme_df.empty:
            st.caption("No matches in your rhyme database.")
        else:
            st.caption("No rhyme data loaded.")

with write_col:
    if not lyrics_df.empty:
        options = ["+ New"] + lyrics_df["title"].tolist()
        selected = st.selectbox("Select lyric", options, label_visibility="collapsed")
    else:
        selected = "+ New"

    if selected == "+ New":
        with st.form("new_lyric", clear_on_submit=True):
            new_title = st.text_input("Title")
            new_content = st.text_area("Write your bars", height=400, placeholder="Start writing...")
            new_status = st.selectbox(
                "Status", list(STATUS_LABELS.keys()),
                format_func=lambda x: STATUS_LABELS[x],
            )
            if st.form_submit_button("Save"):
                if new_title.strip():
                    insert_row("lyrics", {
                        "title": new_title.strip(),
                        "content": new_content,
                        "status": new_status,
                    })
                    st.success(f"Saved '{new_title.strip()}'")
                    st.rerun()
                else:
                    st.error("Title required.")
    else:
        lyric = lyrics_df[lyrics_df["title"] == selected].iloc[0]
        with st.form(f"edit_lyric_{lyric['id']}"):
            edit_title = st.text_input("Title", value=lyric["title"])
            edit_content = st.text_area("Content", value=lyric.get("content") or "", height=400)
            current_status = lyric.get("status", "draft")
            status_index = list(STATUS_LABELS.keys()).index(current_status) if current_status in STATUS_LABELS else 0
            edit_status = st.selectbox(
                "Status", list(STATUS_LABELS.keys()),
                index=status_index,
                format_func=lambda x: STATUS_LABELS[x],
            )
            if st.form_submit_button("Save Changes"):
                update_row("lyrics", int(lyric["id"]), {
                    "title": edit_title.strip(),
                    "content": edit_content,
                    "status": edit_status,
                    "updated_at": today.isoformat(),
                })
                st.success("Saved.")
                st.rerun()

        # --- Stats & Analysis ---
        content = lyric.get("content") or ""
        if content.strip():
            bars = [l for l in content.split("\n") if l.strip()]
            words = len(content.split())
            total_syl = sum(_line_syllables(b) for b in bars)
            avg_syl = total_syl / len(bars) if bars else 0

            st1, st2, st3, st4 = st.columns(4)
            st1.metric("Bars", len(bars))
            st2.metric("Words", words)
            st3.metric("Total Syllables", total_syl)
            st4.metric("Avg Syl/Bar", f"{avg_syl:.1f}")

            # --- Rhyme scheme ---
            if not rhyme_df.empty and bars:
                scheme = _detect_scheme(bars, rhyme_df)
                if scheme:
                    unique_labels = set(l for l in scheme if l != "-")
                    rhyming = sum(1 for l in scheme if scheme.count(l) > 1 and l != "-")
                    density = rhyming / len(scheme) * 100 if scheme else 0

                    with st.expander(f"Rhyme Scheme ({density:.0f}% rhyming)"):
                        SCHEME_COLORS = [
                            "#F44336", "#2196F3", "#4CAF50", "#FF9800",
                            "#9C27B0", "#00BCD4", "#FF5722", "#8BC34A",
                            "#E91E63", "#3F51B5", "#CDDC39", "#795548",
                        ]
                        for i, (bar, label) in enumerate(zip(bars, scheme)):
                            syl = _line_syllables(bar)
                            lw = _last_word(bar)
                            color_idx = ord(label) - 65 if label != "-" else -1
                            color = SCHEME_COLORS[color_idx % len(SCHEME_COLORS)] if color_idx >= 0 else "#666"
                            is_rhyming = scheme.count(label) > 1 and label != "-"
                            weight = "700" if is_rhyming else "400"
                            st.markdown(
                                f'<div style="display:flex;align-items:baseline;gap:8px;margin:2px 0;">'
                                f'<span style="color:{color};font-weight:700;min-width:20px;">{label}</span>'
                                f'<span style="opacity:0.5;min-width:30px;font-size:0.8em;">{syl}s</span>'
                                f'<span style="font-weight:{weight};">{bar}</span>'
                                f'</div>',
                                unsafe_allow_html=True,
                            )

            # --- Suggested rhymes for recent bars ---
            if not rhyme_df.empty and bars:
                last_few = bars[-4:]
                suggestions = {}
                for bar in last_few:
                    lw = _last_word(bar)
                    if lw:
                        rhymes = _find_rhymes(lw, rhyme_df)
                        if rhymes:
                            suggestions[lw] = rhymes[:8]
                if suggestions:
                    with st.expander("Suggested Rhymes (last 4 bars)"):
                        for word, rhymes in suggestions.items():
                            st.markdown(f"**{word}** → {' / '.join(rhymes)}")

            # --- Per-bar syllable breakdown ---
            with st.expander("Syllable Breakdown"):
                _max_syl = max(_line_syllables(b) for b in bars) if bars else 1
                for i, bar in enumerate(bars):
                    syl = _line_syllables(bar)
                    pct = syl / _max_syl if _max_syl > 0 else 0
                    _sc1, _sc2, _sc3 = st.columns([1, 6, 1])
                    _sc1.caption(f"L{i+1}")
                    _sc2.progress(min(pct, 1.0))
                    _sc3.caption(f"{syl}")

        # --- Delete ---
        ck = f"confirm_del_lyric_{lyric['id']}"
        if st.session_state.get(ck):
            st.warning(f"Delete **{lyric['title']}**?")
            yc, nc = st.columns(2)
            if yc.button("Yes", key=f"yes_lyric_{lyric['id']}"):
                delete_row("lyrics", lyric["id"])
                st.session_state.pop(ck, None)
                st.rerun()
            if nc.button("No", key=f"no_lyric_{lyric['id']}"):
                st.session_state.pop(ck, None)
                st.rerun()
        else:
            if st.button("Delete", key=f"del_lyric_{lyric['id']}"):
                st.session_state[ck] = True
                st.rerun()

# --- All Lyrics ---
if not lyrics_df.empty:
    st.divider()
    with st.expander(f"All Lyrics ({len(lyrics_df)})"):
        for _, lyric in lyrics_df.iterrows():
            status = STATUS_LABELS.get(lyric.get("status", "draft"), "Draft")
            content = lyric.get("content") or ""
            bars = len([l for l in content.split("\n") if l.strip()])
            words = len(content.split())
            syl = sum(_line_syllables(l) for l in content.split("\n") if l.strip())
            st.caption(f"[{status}] **{lyric['title']}** | {bars} bars | {words} words | {syl} syllables")
